[profile.default]
src = "src"
out = "out"
test = 'tests'
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chainId = 1 }
